spring:
  application:
    name: NDConsultas-BOT
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false

whatsapp:
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
  api-key: ${WHATSAPP_API_KEY}
  verify-token: ${VERIFY_TOKEN}
  api-version: ${WHATSAPP_API_VERSION:v22.0}

central:
  api-key: ${CENTRAL_API_KEY}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.ndconsultas.bot_whatsapp: INFO
